default:
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/gradle:8.10-jdk21

stages:
  - build

build-jar:
  stage: build
  script:
    - gradle jar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 month
